apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: news-webapi # The name of the app
  namespace: knative-backend # The namespace the app will use
spec:
  template:
    metadata:
      labels:
        app: news-webapi
      annotations:
        sidecar.istio.io/inject: "true" # 禁用istio sidecar注入
        enable-scale-to-zero: "ture" #启用缩放为0，默认true
        autoscaling.knative.dev/target: "10" #设置每个pod并发请求数,默认100
        autoscaling.knative.dev/minScale: "1" #设置最小保留实例数为1,默认100
        autoscaling.knative.dev/maxScale: "5" #设置最小保留实例数为5,默认100
    spec:
      containers:
        - image: harbor.niuguwang.com/gmg_dapeng/stockniu-newsservice-develop:483581b57dceec3742c56dad183753323625e1af # The URL to the image of the app
          ports:
            - name: http1
              containerPort: 80
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
      imagePullSecrets: # harbor 密钥凭证，取k8s里的harbor-niuguwang Secret
        - name: harbor-niuguwang