apiVersion: v1
kind: Secret
metadata:
  name: images-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: harbor.niuguwang.com
type: kubernetes.io/basic-auth
stringData:
  username: chendapeng
  password: qGS8nz1BsJIY
