apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-git-resource
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: "http://47.111.17.136:8088/yangliangbin/csharp-sample-api.git"
